### ISSUE TITLE
Tracking docs changes for recent features

### ISSUE THREAD

**Issue by bbaddepudi** [YugaByte/docs#19]
- AWS instance tags.
- Edit and rolling upgrades not allowed with in transit nodes.
- Cannot stop/remove more than (RF-1)/2 masters.
- Backup to AWS snapshot on bucket naming info.

**Comment by rkarthik007** [comment]
Hi @bbaddepudi - lets use this issue as a master issue, and create/link to a separate issue for each of these items.
