### ISSUE TITLE
create ysql icon 

### ISSUE THREAD

**Issue by ravimurthy** [YugaByte/docs#3]
Need to add a YSQL icon similar to YEDIS and YCQL for use in pages such as these :- 

https://docs.yugabyte.com/latest/develop/client-drivers/java/

**Comment by ivanjovanic** [comment]
Hey @ravimurthy , YCQL and YEDIS currently use Cassandra and Redis icons. Should I create those too (not sure, but we might not be allowed to use them)?

**Comment by rkarthik007** [comment]
This has been updated.
