### ISSUE TITLE
Mac instructions for setting open-file limits may be wrong/obsolete

### ISSUE THREAD

**Issue by m-iancu** [YugaByte/docs#99]
The instructions are currently given in: https://docs.yugabyte.com/latest/quick-start/install/ as
```
c) Make sure that your file limits for kern.maxfiles and kern.maxfilesperproc are 1048576. Edit /etc/sysctl.conf on High Sierra if necessary.
```
But I way to set it in the latest versions (from Yosemite onwards) is to use `plist` files as described [here](https://gist.github.com/tombigel/d503800a282fcadbee14b537735d202c).

**Comment by rkarthik007** [comment]
This has been added to the quick start install page.
